name: go-test
on: 
  push:
    branches:
      - 'main'
      - 'feature/**'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
      - name: Check go version
        run: go version
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Testing go modules
        run: go test ./...
        working-directory: ./src
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Linting go modules
        run: go vet
        working-directory: ./src